name: Everyday

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/everyday.yaml
  workflow_dispatch:
  schedule:
    - cron: "0 6,12,18 * * *" # Run 3x/day until all images downloaded

jobs:
  daily:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
      - name: Fetch Moments album
        run: ruby bin/download-lr.rb
      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "github-actions"
          git add -A content/moments/
          if git diff --cached --quiet; then
            echo "Aucun changement, skip"
            exit 0
          fi
          git commit -m "Sync the moments album"
          git push
